### ISSUE TITLE
Package sb3-contrib

### ISSUE THREAD

**Issue by traversaro** [conda-forge/stable-baselines3-feedstock#16]
### Comment:

Hello everyone @conda-forge/stable-baselines3, once https://github.com/conda-forge/stable-baselines3-feedstock/pull/15 is merged, I am interested also in packaging sb3-contrib (https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) in staged-recipes, I opening this issue to collect any feedback on this.

**Comment by traversaro** [comment]
fyi @YYYasin19 given your interest in the repo.

**Comment by YYYasin19** [comment]
hey, thanks for your work!
I've started the process [here](https://github.com/conda-forge/staged-recipes/pull/23560).

**Comment by pavelzw** [comment]
This is done, right?

**Comment by traversaro** [comment]
Yes: https://github.com/conda-forge/sb3-contrib-feedstock .
